//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECPOST_BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TECPOSTEntities : DbContext
    {
        public TECPOSTEntities()
            : base("name=TECPOSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientModel> ClientModelSet { get; set; }
        public virtual DbSet<MeshModel> MeshModelSet { get; set; }
        public virtual DbSet<CADModel> CADModelSet { get; set; }
        public virtual DbSet<CAMModel> CAMModelSet { get; set; }
    }
}
